### ISSUE TITLE
Provide Linux binary

### ISSUE THREAD

**Issue by probonopd** [Larpon/QuickDownload#1]
Please provide a Linux binary. I think this would be a good use case for [linuxdeployqt](https://github.com/probonopd/linuxdeployqt/).

**Comment by larpon** [comment]
Cool. Maybe I can squeeze in a quick example repository

**Comment by larpon** [comment]
@probonopd - how do you want to use it?

I'm asking because the project itself is for users to compile into their own executable or dynamically load via a *.so plugin - e.g. not anything that comes as an executable Linux binary :)

**Comment by probonopd** [comment]
Ah, never mind, in that case my comment makes no sense, sorry.
