### ISSUE TITLE
Error: Operation canceled when downloading a file from Google Drive

### ISSUE THREAD

**Issue by JaviBonilla** [Larpon/QuickDownload#3]
I tried to download a file from Google Drive with a direct public link but it failed. This is the link for testing.

https://drive.google.com/uc?export=download&id=1eOH1vv5SAoiZK1JWLbOp2biPocockWjg

**Comment by larpon** [comment]
@JaviBonilla - Hi! Thanks for using QuickDownload
I get no errors when I run the following code:
```
Download {
        id: download1

        url: "https://drive.google.com/uc?export=download&id=1eOH1vv5SAoiZK1JWLbOp2biPocockWjg"
        destination: "file:///tmp/infoModel.json"

        running: true

        followRedirects: true
        onRedirected: console.log('Redirected',url,'->',redirectUrl)

        onStarted: console.log('Started download',url)
        onError: console.error(errorString)
        onProgressChanged: console.log(url,'progress:',progress)
        onFinished: console.info(url,'done')

}
```
I get a file in my `/tmp` folder containing:
```
{
"name": "MobileNets",
"version": "1.0",
"modelURL": "https://drive.google.com/file/d/1wy4NMlx0smqMYJBmjMdMIngAgLX-uTik/view?usp=sharing",
"labelsURL": "https://drive.google.com/file/d/132Gw8t-dzBmEC3VqxUe9zwBGPIIMdLkD/view?usp=sharing"
} 
```
I can see that the URL redirects so maybe you're missing `followRedirects: true` ?

**Comment by JaviBonilla** [comment]
Hi @Larpon,

Thanks for testing. The example you provided works, but I am using it in the following way. Let me know if you also have the operation canceled error using this example or if I am doing something wrong.

```
    Download {
            id: download1

            running: false

            followRedirects: true
            overwrite: true
            onRedirected: console.log('Redirected',url,'->',redirectUrl)

            onStarted: console.log('Started download',url)
            onError: console.error(errorString)
            onProgressChanged: console.log(url,'progress:',progress)
            onFinished: console.info(url,'done')

    }
```
Then, I execute it hitting a button in the following way.

```
        download1.url = "https://drive.google.com/uc?export=download&id=1eOH1vv5SAoiZK1JWLbOp2biPocockWjg"
        download1.destination = "file:///tmp/infoModel.json"
        download1.start()

```

**Comment by larpon** [comment]
Good catch! The redirect didn't disconnect properly on 'old' network replies - so signals were fired multiple times resulting in a broken download. Also fixed a warning in the process :+1: - I'll update the `qpm` packages ASAP - until then you can use master or the above commit :)

**Comment by JaviBonilla** [comment]
ok, thanks!

**Comment by larpon** [comment]
qpm packages updated

**Comment by JaviBonilla** [comment]
Hi @Larpon,
Thanks, it works great. I only have a comment, everytime I download the file I can see in the destination folder a new temporary file (i.e. infoModel.json.AApVoE), its size is 0 bytes. Is this file needed? can it be automatically deleted?

**Comment by larpon** [comment]
@JaviBonilla - I observed that as well - it's a bi-product of the way QSaveFile works. To ensure files isn't left in a partial written state - QSaveFile writes to a temporary file - and then moves (i.e. renames) the temporary file when everything is written. Documentation says it should clean up these files - the problem is - it somehow doesn't. I'm not sure why yet - it might be a bug. What Qt version are you using?

You can safely delete it though. But as I tried to explain - QSaveFile should do this "automagically"

**Comment by larpon** [comment]
@JaviBonilla - the bug should be squashed now!

**Comment by JaviBonilla** [comment]
Thanks @Larpon,
I already tested it and it's working perfectly :+1:
