### ISSUE TITLE
Multiple dynamic downloads

### ISSUE THREAD

**Issue by daljit97** [Larpon/QuickDownload#6]
Hi @Larpon, I just came across this project and was wondering something. So in my application the user needs to download multiple files: the user clicks a button and the download starts, the user clicks the button again and a new download starts again (up to 15 times). Now would this be possible with your plugin? I see that you need instantiate a `Download` class in QML for each download, but how can I dynamically generate a `Download` each time I need it? Something like
```
Button{
    function downloadSomething(url)
    {
    // how to create a Download dynamically???
    }
    id: button
    onClicked: downloadSomethingNew(webview.url)
}
```

**Comment by larpon** [comment]
Hi @daljit97 - nice if you can find use for this project 🙂

One solution would be to create `Download` elements on the fly with [dynamic object creation](https://doc.qt.io/qt-5/qtqml-javascript-dynamicobjectcreation.html).

Maybe wrap the functionality up in a `DownloadManager` QML type that connects to each new download's signals and keep internal track of who's done etc. 

That's one way to do it 🤔🙂

**Comment by daljit97** [comment]
@Larpon yeah I thought about using components as well. Your idea about constructing a `DownloadManager` seems nice although I need to check how long will that take. Thanks a lot for your input.

**Comment by larpon** [comment]
No problem 🙂 Happy coding!
